# Pontos faciais para reconhecimento

## Bibliotecas necessárias 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import pathlib
import random

### Diretório do arquivo

In [3]:
data_dir = pathlib.Path(r'C:\Users\dueir\Turing\Areas\CV\Face Hash\Data\features_rostos_estevam.csv')

In [34]:
test_dir = pathlib.Path(r'C:\Users\dueir\Turing\Areas\CV\Face Hash\Data\turing_faces_distances.csv')

In [7]:
data = pd.read_csv(data_dir)

In [35]:
test_data = pd.read_csv(test_dir)

Vamos ver como é nosso arquivo

In [8]:
data.head()

Unnamed: 0         0         1    2         3         4         5  \
0           0  0.260142  0.046183  1.0  0.951472  0.854369  0.519104   
1           1  0.254773  0.058447  1.0  0.957970  0.832973  0.495182   
2           2  0.253177  0.047306  1.0  0.944648  0.844557  0.522190   
3           3  0.237653  0.043372  1.0  0.959052  0.829501  0.493206   
4           4  0.252994  0.034398  1.0  0.986235  0.852079  0.482434   

          6         7         8  ...        21        22        23        24  \
0  0.277540  0.280888  0.432679  ...  0.179145  0.162710 -0.056749  0.255016   
1  0.283555  0.246511  0.392400  ...  0.196968  0.177396 -0.057979  0.239740   
2  0.289724  0.287694  0.450007  ...  0.184831  0.179927 -0.061107  0.250068   
3  0.255357  0.292196  0.351102  ...  0.212722  0.210850 -0.059389  0.268917   
4  0.385506  0.315833  0.442231  ...  0.134067  0.146044 -0.052632  0.258137   

         25        26        27        28        29           Nome  
0  0.239297  0.375422  0.359321  0.654896  0.302772  Aaron_Peirsol  
1  0.219459  0.368476  0.328212  0.669961  0.280692  Aaron_Peirsol  
2  0.225604  0.363262  0.344334  0.626515  0.295239  Aaron_Peirsol  
3  0.256376  0.357886  0.388767  0.751863  0.367562  Aaron_Peirsol  
4  0.239913  0.365022  0.321053  0.646611  0.281889   Aaron_Sorkin  

[5 rows x 32 columns]

In [9]:
data.Nome.value_counts()

George_W_Bush         530
Colin_Powell          236
Tony_Blair            144
Donald_Rumsfeld       121
Gerhard_Schroeder     109
                     ... 
Bruce_Van_De_Velde      2
Lord_Hutton             2
Sharon_Davis            2
Tyra_Banks              2
Martin_McCauley         2
Name: Nome, Length: 1680, dtype: int64

Vemos que ele é desbalanceado em termos de pessoas

In [10]:
data.shape

(9164, 32)

Temos 9164 imagens de 1680 pessoas diferentes, com 30 características

In [11]:
data.columns

Index(['Unnamed: 0', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', 'Nome'],
      dtype='object')

In [12]:
data = data.drop('Unnamed: 0', axis=1)

In [13]:
data.isnull().values.any()

True

In [14]:
data = data.fillna(0)

## Abordagem

A ideia inicial aqui será criar novas features, cada nova feature será o módulo da subtração das distâncias

In [15]:
cols=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', 'Same']
df = pd.DataFrame(columns=cols)

In [16]:
names = pd.unique(data['Nome'])

In [17]:
encoded_data = data.copy()
encoded_data['Nome'].replace(names, np.arange(1680), inplace=True)

In [18]:
npdata = encoded_data.to_numpy()
npdata

array([[2.60142002e-01, 4.61829830e-02, 1.00000000e+00, ...,
        6.54895569e-01, 3.02771735e-01, 0.00000000e+00],
       [2.54773110e-01, 5.84466762e-02, 1.00000000e+00, ...,
        6.69961043e-01, 2.80692127e-01, 0.00000000e+00],
       [2.53176901e-01, 4.73057713e-02, 1.00000000e+00, ...,
        6.26514952e-01, 2.95238825e-01, 0.00000000e+00],
       ...,
       [2.49118779e-01, 6.23825972e-02, 1.00000000e+00, ...,
        7.25303734e-01, 2.88254858e-01, 1.67900000e+03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.67900000e+03],
       [2.40977548e-01, 3.46110289e-02, 1.00000000e+00, ...,
        6.43695094e-01, 2.79411246e-01, 1.67900000e+03]])

In [19]:
for i in range(len(npdata)):
    if np.count_nonzero(npdata[i]) < 5:
        npdata = np.delete(npdata, i, 0)
        print("Deleted row", i)

Deleted row 9
Deleted row 10
Deleted row 14
Deleted row 30
Deleted row 41
Deleted row 46
Deleted row 53
Deleted row 54
Deleted row 70
Deleted row 88
Deleted row 94
Deleted row 97
Deleted row 107
Deleted row 110
Deleted row 113
Deleted row 141
Deleted row 153
Deleted row 156
Deleted row 161
Deleted row 196
Deleted row 198
Deleted row 225
Deleted row 226
Deleted row 230
Deleted row 265
Deleted row 276
Deleted row 277
Deleted row 306
Deleted row 307
Deleted row 310
Deleted row 331
Deleted row 347
Deleted row 348
Deleted row 350
Deleted row 377
Deleted row 386
Deleted row 387
Deleted row 402
Deleted row 435
Deleted row 437
Deleted row 452
Deleted row 475
Deleted row 511
Deleted row 514
Deleted row 527
Deleted row 531
Deleted row 532
Deleted row 551
Deleted row 564
Deleted row 566
Deleted row 583
Deleted row 585
Deleted row 587
Deleted row 589
Deleted row 596
Deleted row 602
Deleted row 608
Deleted row 609
Deleted row 610
Deleted row 619
Deleted row 620
Deleted row 633
Deleted row 635
Delet

Deleted row 5465
Deleted row 5473
Deleted row 5488
Deleted row 5489
Deleted row 5507
Deleted row 5508
Deleted row 5514
Deleted row 5515
Deleted row 5516
Deleted row 5517
Deleted row 5518
Deleted row 5519
Deleted row 5528
Deleted row 5558
Deleted row 5561
Deleted row 5562
Deleted row 5563
Deleted row 5567
Deleted row 5575
Deleted row 5595
Deleted row 5606
Deleted row 5615
Deleted row 5618
Deleted row 5622
Deleted row 5659
Deleted row 5672
Deleted row 5684
Deleted row 5685
Deleted row 5705
Deleted row 5708
Deleted row 5716
Deleted row 5717
Deleted row 5720
Deleted row 5730
Deleted row 5733
Deleted row 5735
Deleted row 5737
Deleted row 5745
Deleted row 5753
Deleted row 5774
Deleted row 5800
Deleted row 5806
Deleted row 5810
Deleted row 5813
Deleted row 5858
Deleted row 5859
Deleted row 5871
Deleted row 5873
Deleted row 5893
Deleted row 5902
Deleted row 5906
Deleted row 5914
Deleted row 5916
Deleted row 5919
Deleted row 5921
Deleted row 5922
Deleted row 5933
Deleted row 5944
Deleted row 59

IndexError: index 8341 is out of bounds for axis 0 with size 8341

In [ ]:
npdata.shape

In [ ]:
npdata[6][-1]

In [20]:
different = 11
equals = 38
shape = (npdata.shape[0]*(different+1), npdata.shape[1])
npdf = np.zeros(shape)
i = 0
for first_row in (range(0, npdata.shape[0])):
    numbers = np.array(random.sample(range(0,npdata.shape[0]),different))
    numbers=numbers[numbers!=first_row]
    equal = first_row+1
    while (npdata[first_row][-1] == npdata[equal][-1]) and (equal < first_row+equals):
        numbers = np.append(numbers, equal)
        equal+=1
    for second_row in numbers:
        npdf[i] = np.absolute(npdata[first_row] - npdata[second_row])
        npdf[i][30] = int(npdf[i][30] == 0) #1 se corresponder a uma mesma pessoa
        i += 1
print(i)

IndexError: index 100092 is out of bounds for axis 0 with size 100092

In [21]:
npdf.shape

(100092, 31)

In [22]:
lenght = len(npdf)
print(lenght)
i=0
while i < lenght:
    if np.count_nonzero(npdf[i]) < 20:
        npdf = np.delete(npdf, i, 0)
        print("Deleted row", i)
        lenght-=1
        i-=1
    i+=1

100092
Deleted row 1258
Deleted row 7474
Deleted row 34214
Deleted row 45515
Deleted row 53854
Deleted row 93422
Deleted row 93505
Deleted row 99327
Deleted row 99333


In [23]:
npdf.shape

(100083, 31)

In [24]:
df = pd.DataFrame(npdf, columns=cols)
print(df.Same.sum()/npdf.shape[0])

0.525234055733741


In [25]:
df.head(10)

0         1    2         3         4         5         6         7  \
0  0.010589  0.013579  0.0  0.005163  0.039005  0.049551  0.008059  0.035847   
1  0.012477  0.028077  0.0  0.023060  0.024899  0.013702  0.033727  0.028860   
2  0.018715  0.018708  0.0  0.025540  0.003731  0.013235  0.020087  0.026296   
3  0.021903  0.007743  0.0  0.034564  0.020547  0.007434  0.036993  0.024965   
4  0.030589  0.032386  0.0  0.008002  0.052905  0.045398  0.030291  0.061235   
5  0.018884  0.011952  0.0  0.007009  0.034745  0.026809  0.044384  0.009885   
6  0.000812  0.018585  0.0  0.047394  0.015324  0.019710  0.060742  0.027344   
7  0.020583  0.001209  0.0  0.022340  0.017113  0.029178  0.030116  0.067617   
8  0.038918  0.025141  0.0  0.011436  0.008503  0.012210  0.000674  0.010392   
9  0.004322  0.016354  0.0  0.025785  0.002091  0.019080  0.022302  0.016522   

          8         9  ...        21        22        23        24        25  \
0  0.046416  0.022526  ...  0.083338  0.079999  0.014985  0.034065  0.026296   
1  0.108535  0.022327  ...  0.037921  0.002345  0.000929  0.014178  0.017449   
2  0.070434  0.001369  ...  0.008795  0.035299  0.009342  0.016766  0.001759   
3  0.088420  0.011616  ...  0.014139  0.014193  0.006084  0.015056  0.003902   
4  0.065768  0.013884  ...  0.007455  0.016203  0.003495  0.010413  0.033739   
5  0.072890  0.006552  ...  0.001844  0.029053  0.006786  0.007380  0.010439   
6  0.079020  0.029189  ...  0.039841  0.050343  0.003447  0.001799  0.009425   
7  0.101101  0.004697  ...  0.039119  0.032549  0.001486  0.001186  0.013717   
8  0.032844  0.000577  ...  0.019317  0.022646  0.006774  0.003585  0.000435   
9  0.017875  0.001108  ...  0.008786  0.061106  0.002909  0.022679  0.009903   

         26        27        28        29  Same  
0  0.061669  0.081823  0.024859  0.018292   0.0  
1  0.075352  0.056348  0.048257  0.000258   0.0  
2  0.010956  0.020723  0.065753  0.010958   0.0  
3  0.023021  0.042565  0.066505  0.006075   0.0  
4  0.030395  0.053626  0.048242  0.081533   0.0  
5  0.002674  0.044026  0.183684  0.067819   0.0  
6  0.044717  0.000492  0.033807  0.050975   0.0  
7  0.004000  0.000614  0.113724  0.002517   0.0  
8  0.047197  0.031095  0.005999  0.055120   0.0  
9  0.044855  0.035413  0.014080  0.001030   0.0  

[10 rows x 31 columns]

In [ ]:
df.to_csv('facial_differences.csv', index=False)

## Modelo 

In [27]:
from sklearn.model_selection import train_test_split

train_y = df.Same
train_x = df.drop(['Same'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.25, random_state=42)

In [151]:
from sklearn.linear_model import LogisticRegression

lrc = LogisticRegression().fit(X_train, y_train)
lrc.score(X_test, y_test)

C:\Users\dueir\anaconda3\envs\PythonAI\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.7053847830826248

In [152]:
y_train.sum()/len(y_train)

0.5647200744142783

In [153]:
y_test.sum()/len(y_test)

0.5674732940919991

In [28]:
from sklearn import ensemble
original_params = {'n_estimators': 1000, 'max_leaf_nodes': 4, 'max_depth': None, 'random_state': 2,
                   'min_samples_split': 5}
params=dict(original_params)
clf = ensemble.GradientBoostingClassifier(**params)
clf.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=None,
                           max_features=None, max_leaf_nodes=4,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=5,
                           min_weight_fraction_leaf=0.0, n_estimators=1000,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=2, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [29]:
clf.score(X_test, y_test)

0.7529675072938732

In [56]:
import pickle
#save the model to disk
filename = 'gradient_boosting_faces_clf.sav'
pickle.dump(clf, open(filename, 'wb'))

#load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))

## Testando com o dataset do Turing 

In [44]:
test_data.columns

Index(['Unnamed: 0', 'nome', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
       '22', '23', '24', '25', '26', '27', '28', '29'],
      dtype='object')

In [45]:
test_data = test_data.drop('Unnamed: 0', axis=1)

In [46]:
test_data.nome.value_counts()

Edu       4
Azank     3
Mura      2
Cola      2
Enzo      2
Paulo     2
Ariel     2
Noel      2
Nelson    2
Fill      2
Luisa     2
Gui       2
Camila    2
Koji      1
Victor    1
Name: nome, dtype: int64

In [47]:
cols=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', 'Same']
df2 = pd.DataFrame(columns=cols)

In [48]:
names2 = pd.unique(test_data['nome'])

In [49]:
encoded_data2 = test_data.copy()
encoded_data2['nome'].replace(names2, np.arange(15), inplace=True)

In [50]:
npdata2 = encoded_data2.to_numpy()
npdata2

array([[ 0.        ,  0.25428366,  0.03542707,  1.        ,  0.97753248,
         0.85326208,  0.52004198,  0.34309569,  0.30581136,  0.35610583,
         0.05084665,  0.07344516,  0.28253786,  0.13570871,  0.22040789,
         0.37890446,  0.40906189,  0.40369374,  0.27777036,  0.14169193,
         0.92340848,  0.49338408,  0.28143276,  0.28904331, -0.06497071,
         0.28385856,  0.25124176,  0.29312802,  0.29055787,  0.7035968 ,
         0.29812617],
       [ 1.        ,  0.2751719 ,  0.04408635,  1.        ,  0.90957254,
         0.74695803,  0.43989212,  0.21818622,  0.21160113,  0.39760714,
         0.03614196,  0.07830757,  0.19878075,  0.10240221,  0.25299369,
         0.43693777,  0.40197664,  0.39116553,  0.34987197,  0.17478994,
         0.87144679,  0.53934632,  0.16460125,  0.18674958, -0.06324842,
         0.3058034 ,  0.26858402,  0.38706405,  0.38706405,  0.71651187,
         0.27814753],
       [ 1.        ,  0.28399087,  0.04796744,  1.        ,  0.97422697,
       

In [51]:
for i in range(len(npdata2)):
    if np.count_nonzero(npdata2[i]) < 5:
        npdata2 = np.delete(npdata2, i, 0)
        print("Deleted row", i)

In [52]:
different = 2
equals = 5
shape = (npdata2.shape[0]*(different+1), npdata2.shape[1])
npdf = np.zeros(shape)
i = 0
for first_row in (range(0, npdata2.shape[0])):
    numbers = np.array(random.sample(range(0,npdata2.shape[0]),different))
    numbers=numbers[numbers!=first_row]
    equal = first_row+1
    while (npdata2[first_row][-1] == npdata2[equal][-1]) and (equal < first_row+equals):
        numbers = np.append(numbers, equal)
        equal+=1
    for second_row in numbers:
        npdf[i] = np.absolute(npdata2[first_row] - npdata2[second_row])
        npdf[i][30] = int(npdf[i][30] == 0) #1 se corresponder a uma mesma pessoa
        i += 1
print(i)

IndexError: index 31 is out of bounds for axis 0 with size 31

In [53]:
df = pd.DataFrame(npdf, columns=cols)

In [54]:
test_y = df.Same
test_x = df.drop(['Same'], axis=1)

In [55]:
clf.score(test_x, test_y)

0.8709677419354839